# Generated by Django 2.2.3 on 2019-07-26 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='portfolio')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 26, 13, 8, 46, 879809))),
            ],
        ),
    ]
